"""initial migrations

Revision ID: 216792151ac3
Revises: 
Create Date: 2026-02-07 19:08:16.184255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '216792151ac3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('codigo_dre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abreviacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dres_ativo'), 'dres', ['ativo'], unique=False)
    op.create_index(op.f('ix_dres_codigo_dre'), 'dres', ['codigo_dre'], unique=True)
    op.create_table('ues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('codigo_ue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dre_id'], ['dres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ues_ativo'), 'ues', ['ativo'], unique=False)
    op.create_index(op.f('ix_ues_codigo_ue'), 'ues', ['codigo_ue'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ues_codigo_ue'), table_name='ues')
    op.drop_index(op.f('ix_ues_ativo'), table_name='ues')
    op.drop_table('ues')
    op.drop_index(op.f('ix_dres_codigo_dre'), table_name='dres')
    op.drop_index(op.f('ix_dres_ativo'), table_name='dres')
    op.drop_table('dres')
    # ### end Alembic commands ###
