"""remover_auditoria_projetos_sociais_escolares

Revision ID: 3818fe44871b
Revises: 9b8c7d6e5f4a
Create Date: 2026-02-21 21:16:23.918528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3818fe44871b'
down_revision: Union[str, None] = '9b8c7d6e5f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projetos_sociais_escolares_ativo', table_name='projetos_sociais_escolares')
    op.drop_index('uq_projetos_sociais_escolares_ue_projeto', table_name='projetos_sociais_escolares')
    op.drop_column('projetos_sociais_escolares', 'ativo')
    op.drop_column('projetos_sociais_escolares', 'alterado_em')
    op.drop_column('projetos_sociais_escolares', 'criado_em')
    op.drop_column('projetos_sociais_escolares', 'excluido_em')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos_sociais_escolares', sa.Column('excluido_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projetos_sociais_escolares', sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projetos_sociais_escolares', sa.Column('alterado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projetos_sociais_escolares', sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('uq_projetos_sociais_escolares_ue_projeto', 'projetos_sociais_escolares', ['ue_id', 'projeto_social_id'], unique=True)
    op.create_index('ix_projetos_sociais_escolares_ativo', 'projetos_sociais_escolares', ['ativo'], unique=False)
    # ### end Alembic commands ###
