"""excluir_endereco_tabela_projeto_social

Revision ID: 49b7db13aaad
Revises: 7dad5c8fc36f
Create Date: 2026-02-21 10:48:22.899712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49b7db13aaad'
down_revision: Union[str, None] = '7dad5c8fc36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos_sociais', 'endereco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos_sociais', sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
