"""initial_migrations

Revision ID: 49cbd2f43387
Revises: 
Create Date: 2026-02-23 02:15:09.949672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49cbd2f43387'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('opcional', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xs', sa.Integer(), nullable=True),
    sa.Column('lg', sa.Integer(), nullable=True),
    sa.Column('md', sa.Integer(), nullable=True),
    sa.Column('sm', sa.Integer(), nullable=True),
    sa.Column('readonly', sa.Boolean(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('mascara', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('placeholder', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'label', 'formulario_id', name='uq_campo_nome_label_formulario')
    )
    op.create_index(op.f('ix_campos_ativo'), 'campos', ['ativo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campos_ativo'), table_name='campos')
    op.drop_table('campos')
    # ### end Alembic commands ###
