"""criar_tabela_categorias

Revision ID: 7dad5c8fc36f
Revises: f0736cc4876e
Create Date: 2026-02-21 07:13:07.113134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dad5c8fc36f'
down_revision: Union[str, None] = 'f0736cc4876e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_ativo'), 'categorias', ['ativo'], unique=False)
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=True)
    # remove foreign key constraint from projetos_sociais to situacoes
    op.drop_constraint('projetos_sociais_situacao_id_fkey', 'projetos_sociais', type_='foreignkey')
    op.drop_index('ix_situacoes_ativo', table_name='situacoes')
    op.drop_index('ix_situacoes_nome', table_name='situacoes')
    op.drop_table('situacoes')
    op.add_column('projetos_sociais', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projetos_sociais', 'categorias', ['categoria_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projetos_sociais', 'situacao_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos_sociais', sa.Column('situacao_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projetos_sociais', type_='foreignkey')
    op.create_foreign_key('projetos_sociais_situacao_id_fkey', 'projetos_sociais', 'situacoes', ['situacao_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projetos_sociais', 'categoria_id')
    op.create_table('situacoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('alterado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('excluido_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='situacoes_pkey')
    )
    op.create_index('ix_situacoes_nome', 'situacoes', ['nome'], unique=True)
    op.create_index('ix_situacoes_ativo', 'situacoes', ['ativo'], unique=False)
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_ativo'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
