"""create_table_situacoes_publicos_alvos

Revision ID: 88b407f891fb
Revises: e2d653ed6efd
Create Date: 2026-02-20 19:46:40.686568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88b407f891fb'
down_revision: Union[str, None] = 'e2d653ed6efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicos_alvos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicos_alvos_ativo'), 'publicos_alvos', ['ativo'], unique=False)
    op.create_index(op.f('ix_publicos_alvos_nome'), 'publicos_alvos', ['nome'], unique=True)
    op.create_table('situacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_situacoes_ativo'), 'situacoes', ['ativo'], unique=False)
    op.create_index(op.f('ix_situacoes_nome'), 'situacoes', ['nome'], unique=True)
    op.add_column('projetos_sociais', sa.Column('publico_alvo_id', sa.Integer(), nullable=False))
    op.add_column('projetos_sociais', sa.Column('situacao_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projetos_sociais', 'publicos_alvos', ['publico_alvo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projetos_sociais', 'situacoes', ['situacao_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projetos_sociais', 'situacao')
    op.drop_column('projetos_sociais', 'publico_alvo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos_sociais', sa.Column('publico_alvo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projetos_sociais', sa.Column('situacao', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projetos_sociais', type_='foreignkey')
    op.drop_constraint(None, 'projetos_sociais', type_='foreignkey')
    op.drop_column('projetos_sociais', 'situacao_id')
    op.drop_column('projetos_sociais', 'publico_alvo_id')
    op.drop_index(op.f('ix_situacoes_nome'), table_name='situacoes')
    op.drop_index(op.f('ix_situacoes_ativo'), table_name='situacoes')
    op.drop_table('situacoes')
    op.drop_index(op.f('ix_publicos_alvos_nome'), table_name='publicos_alvos')
    op.drop_index(op.f('ix_publicos_alvos_ativo'), table_name='publicos_alvos')
    op.drop_table('publicos_alvos')
    # ### end Alembic commands ###
