"""create_table_projetos_sociais

Revision ID: 92d62a19dbb6
Revises: 216792151ac3
Create Date: 2026-02-08 12:52:11.876513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92d62a19dbb6'
down_revision: Union[str, None] = '216792151ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projetos_sociais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publico_alvo', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_sociais_ativo'), 'projetos_sociais', ['ativo'], unique=False)
    op.create_index(op.f('ix_projetos_sociais_nome'), 'projetos_sociais', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projetos_sociais_nome'), table_name='projetos_sociais')
    op.drop_index(op.f('ix_projetos_sociais_ativo'), table_name='projetos_sociais')
    op.drop_table('projetos_sociais')
    # ### end Alembic commands ###
