"""create_table_projetos_sociais_escolares

Revision ID: 933eb61dd558
Revises: 92d62a19dbb6
Create Date: 2026-02-08 13:25:06.860157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '933eb61dd558'
down_revision: Union[str, None] = '92d62a19dbb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projetos_sociais_escolares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('projeto_social_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_social_id'], ['projetos_sociais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_sociais_escolares_ativo'), 'projetos_sociais_escolares', ['ativo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projetos_sociais_escolares_ativo'), table_name='projetos_sociais_escolares')
    op.drop_table('projetos_sociais_escolares')
    # ### end Alembic commands ###
