"""remover_ue_id_tabela_projeto_social

Revision ID: f0736cc4876e
Revises: 88b407f891fb
Create Date: 2026-02-21 06:11:48.701938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0736cc4876e'
down_revision: Union[str, None] = '88b407f891fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projetos_sociais_ue_id_fkey', 'projetos_sociais', type_='foreignkey')
    op.drop_column('projetos_sociais', 'ue_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos_sociais', sa.Column('ue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('projetos_sociais_ue_id_fkey', 'projetos_sociais', 'ues', ['ue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
