"""initial_migrations

Revision ID: fbd17311dc6b
Revises: 
Create Date: 2026-02-21 16:02:42.924574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbd17311dc6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_ativo'), 'categorias', ['ativo'], unique=False)
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=True)
    op.create_table('dres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('codigo_dre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abreviacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dres_ativo'), 'dres', ['ativo'], unique=False)
    op.create_index(op.f('ix_dres_codigo_dre'), 'dres', ['codigo_dre'], unique=True)
    op.create_table('publicos_alvos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicos_alvos_ativo'), 'publicos_alvos', ['ativo'], unique=False)
    op.create_index(op.f('ix_publicos_alvos_nome'), 'publicos_alvos', ['nome'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_ativo'), 'usuarios', ['ativo'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('projetos_sociais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publico_alvo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publico_alvo_id'], ['publicos_alvos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_sociais_ativo'), 'projetos_sociais', ['ativo'], unique=False)
    op.create_index(op.f('ix_projetos_sociais_nome'), 'projetos_sociais', ['nome'], unique=True)
    op.create_table('ues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('codigo_ue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dre_id'], ['dres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ues_ativo'), 'ues', ['ativo'], unique=False)
    op.create_index(op.f('ix_ues_codigo_ue'), 'ues', ['codigo_ue'], unique=True)
    op.create_table('projetos_sociais_escolares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('projeto_social_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_social_id'], ['projetos_sociais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_sociais_escolares_ativo'), 'projetos_sociais_escolares', ['ativo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projetos_sociais_escolares_ativo'), table_name='projetos_sociais_escolares')
    op.drop_table('projetos_sociais_escolares')
    op.drop_index(op.f('ix_ues_codigo_ue'), table_name='ues')
    op.drop_index(op.f('ix_ues_ativo'), table_name='ues')
    op.drop_table('ues')
    op.drop_index(op.f('ix_projetos_sociais_nome'), table_name='projetos_sociais')
    op.drop_index(op.f('ix_projetos_sociais_ativo'), table_name='projetos_sociais')
    op.drop_table('projetos_sociais')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_ativo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_publicos_alvos_nome'), table_name='publicos_alvos')
    op.drop_index(op.f('ix_publicos_alvos_ativo'), table_name='publicos_alvos')
    op.drop_table('publicos_alvos')
    op.drop_index(op.f('ix_dres_codigo_dre'), table_name='dres')
    op.drop_index(op.f('ix_dres_ativo'), table_name='dres')
    op.drop_table('dres')
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_ativo'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
